server:
  port: 8080
spring:
  redis:
    master:
      host: 127.0.0.1
      port: 6379
    slaves:
      - host: 127.0.0.1
        port: 6479
      - host: 127.0.0.1
        port: 6579
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:commerceDB
  jpa:
    show-sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true
      path: /h2-console